### PR TITLE
Documents don't have a the default 'created_at' for acts as event

### PR DESCRIPTION
**Pull request by tgsoverly**
This was causing searching in open project on a document to throw a 500 error.

### CODE REVIEW

**Comment by hschink** [comment]
@tgsoverly thanks a lot for your PR! :+1: However, I'd like have a spec for this. May I ask you to provide one?

**Comment by tgsoverly** [comment]
@hschink I would be happy to.  Am I missing something or are there some of the testing files that aren't committed?  How do you run the specs for this project?

**Comment by hschink** [comment]
@tgsoverly you start the plug-in specs from the openproject root:

```
openproject> rspec path/to/openproject-documents
```

Which testing files do you miss?

**Comment by tgsoverly** [comment]
@hschink I see that the "spec_helper" references the openproject core and based on your comment, does this mean I have to test this within an installation of openproject and I can not do the following:

```
git clone git@github.com:opf/openproject-documents.git
cd openproject-documents
rspec
```

I will have to do some cloning/installation, I thought you would be able to test in isolation.  Makes sense now.

**Comment by tgsoverly** [comment]
@hschink Updated.  You guys squash?

**Comment by hschink** [comment]
@tgsoverly please excuse my late reply. We'll need some time to check and merge this PR. But, at first sight, it looks quite good. Again, thanks a lot!

**Comment by hschink** [comment]
Merged in 07a821c6d6f07654d7f85643544663155b909cbf as well as modified tests (d77924de292987e770c148e4f81ef0bd2cd2ba4c) and readme (38789604ff1f51ef085f7126c88a4fa5799dd8a6)

Thanks again @tgsoverly! Waiting for your next PR! :smiley:

**Pull request closed without merging**
